### ISSUE TITLE
Realm write outside of transaction

### ISSUE THREAD

**Issue by Zhuinden** [soulcramer/NotifyMoe-Android-App#1]
https://github.com/soulcramer/NotifyMoe-Android-App/blob/a4d11cf778701334e4e3e246582b3445729d5352/app/src/main/java/studio/lunabee/arn/db/UserDao.kt#L14

Are you sure this works? I'd expect you should use `runTransactionSync` instead of `doWithRealm`.

**Comment by soulcramer** [comment]
https://github.com/Zhuinden/realm-monarchy/blob/31fcb1103263621deea86ee5899d99bb4161c2a1/monarchy/src/main/java/com/zhuinden/monarchy/Monarchy.java#L153-L160 
When I checked the differences, it seemed to me that they were the same 🤔

**Comment by soulcramer** [comment]
Ahh nope, my bad I understand the difference now.
